openapi: 3.0.3
info:
  title: Fly-Fleet API
  description: Private Jet Charter Brokerage Platform API
  version: 1.0.0
  contact:
    name: Fly-Fleet Support
    email: contact@fly-fleet.com
  license:
    name: Private
servers:
  - url: http://localhost:3000
    description: Development server
tags:
  - name: quotes
    description: Quote request management
  - name: contact
    description: Contact form handling
  - name: airports
    description: Airport search functionality
  - name: content
    description: Content management system
  - name: faqs
    description: FAQ management
  - name: analytics
    description: Event tracking and analytics
  - name: whatsapp
    description: WhatsApp integration
  - name: webhooks
    description: External service webhooks
  - name: recaptcha
    description: reCAPTCHA verification
  - name: seo
    description: SEO metadata generation
  - name: admin
    description: Administrative operations
paths:
  /api/admin/email-activities:
    get:
      summary: List admin\email-activities\route.ts
      description: GET operation for admin\email-activities\route.ts
      tags:
        - admin\email-activities\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of results
        - name: offset
          in: query
          schema:
            type: integer
          description: Pagination offset
        - name: status
          in: query
          schema:
            type: string
          description: Filter by status
  /api/admin/email-stats:
    get:
      summary: List admin\email-stats\route.ts
      description: GET operation for admin\email-stats\route.ts
      tags:
        - admin\email-stats\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
  /api/admin/quotes:
    get:
      summary: List admin\quotes\route.ts
      description: GET operation for admin\quotes\route.ts
      tags:
        - admin\quotes\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
      security:
        - AdminAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of results
        - name: offset
          in: query
          schema:
            type: integer
          description: Pagination offset
        - name: status
          in: query
          schema:
            type: string
          description: Filter by status
    post:
      summary: Create admin\quotes\route.ts
      description: POST operation for admin\quotes\route.ts
      tags:
        - admin\quotes\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
      security:
        - AdminAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of results
        - name: offset
          in: query
          schema:
            type: integer
          description: Pagination offset
        - name: status
          in: query
          schema:
            type: string
          description: Filter by status
  /api/airports:
    get:
      summary: List airports\route.ts
      description: GET operation for airports\route.ts
      tags:
        - airports\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: q
          in: query
          schema:
            type: string
          description: Search query
        - name: locale
          in: query
          schema:
            type: string
            enum:
              - es
              - en
              - pt
          description: Language locale
  /api/contact:
    post:
      summary: Create contact\route.ts
      description: POST operation for contact\route.ts
      tags:
        - contact\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactFormSchema'
  /api/content:
    get:
      summary: List content\route.ts
      description: GET operation for content\route.ts
      tags:
        - content\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: locale
          in: query
          schema:
            type: string
            enum:
              - es
              - en
              - pt
          description: Language locale
        - name: action
          in: query
          schema:
            type: string
          description: Action to perform
    post:
      summary: Create content\route.ts
      description: POST operation for content\route.ts
      tags:
        - content\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: locale
          in: query
          schema:
            type: string
            enum:
              - es
              - en
              - pt
          description: Language locale
        - name: action
          in: query
          schema:
            type: string
          description: Action to perform
  /api/content/{page}/{locale}:
    get:
      summary: List content\[page]\[locale]\route.ts
      description: GET operation for content\[page]\[locale]\route.ts
      tags:
        - content\[page]\[locale]\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: page
          in: path
          required: true
          schema:
            type: string
          description: Page parameter
        - name: locale
          in: path
          required: true
          schema:
            type: string
          description: Locale parameter
  /api/faqs:
    get:
      summary: List faqs\route.ts
      description: GET operation for faqs\route.ts
      tags:
        - faqs\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: locale
          in: query
          schema:
            type: string
            enum:
              - es
              - en
              - pt
          description: Language locale
        - name: action
          in: query
          schema:
            type: string
          description: Action to perform
    post:
      summary: Create faqs\route.ts
      description: POST operation for faqs\route.ts
      tags:
        - faqs\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: locale
          in: query
          schema:
            type: string
            enum:
              - es
              - en
              - pt
          description: Language locale
        - name: action
          in: query
          schema:
            type: string
          description: Action to perform
  /api/faqs/{locale}:
    get:
      summary: List faqs\[locale]\route.ts
      description: GET operation for faqs\[locale]\route.ts
      tags:
        - faqs\[locale]\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of results
        - name: category
          in: query
          schema:
            type: string
          description: Filter by category
        - name: search
          in: query
          schema:
            type: string
          description: Search term
        - name: grouped
          in: query
          schema:
            type: boolean
          description: Group results
        - name: locale
          in: path
          required: true
          schema:
            type: string
          description: Locale parameter
  /api/health:
    get:
      summary: List health\route.ts
      description: GET operation for health\route.ts
      tags:
        - health\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
  /api/quote:
    post:
      summary: Create quote\route.ts
      description: POST operation for quote\route.ts
      tags:
        - quote\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request body schema (auto-detected)
  /api/quotes/{id}/status:
    get:
      summary: List quotes\[id]\status\route.ts
      description: GET operation for quotes\[id]\status\route.ts
      tags:
        - quotes\[id]\status\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
      security:
        - AdminAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Id parameter
    patch:
      summary: Partially update quotes\[id]\status\route.ts
      description: PATCH operation for quotes\[id]\status\route.ts
      tags:
        - quotes\[id]\status\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '500':
          $ref: '#/components/responses/InternalError'
      security:
        - AdminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteStatusUpdateSchema'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Id parameter
  /api/recaptcha/verify:
    get:
      summary: List recaptcha\verify\route.ts
      description: GET operation for recaptcha\verify\route.ts
      tags:
        - recaptcha\verify\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create recaptcha\verify\route.ts
      description: POST operation for recaptcha\verify\route.ts
      tags:
        - recaptcha\verify\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/seo/{page}/{locale}:
    get:
      summary: List seo\[page]\[locale]\route.ts
      description: GET operation for seo\[page]\[locale]\route.ts
      tags:
        - seo\[page]\[locale]\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
      parameters:
        - name: page
          in: path
          required: true
          schema:
            type: string
          description: Page parameter
        - name: locale
          in: path
          required: true
          schema:
            type: string
          description: Locale parameter
  /api/webhooks/resend:
    get:
      summary: List webhooks\resend\route.ts
      description: GET operation for webhooks\resend\route.ts
      tags:
        - webhooks\resend\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create webhooks\resend\route.ts
      description: POST operation for webhooks\resend\route.ts
      tags:
        - webhooks\resend\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
  /api/webhooks/resend/test:
    get:
      summary: List webhooks\resend\test\route.ts
      description: GET operation for webhooks\resend\test\route.ts
      tags:
        - webhooks\resend\test\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create webhooks\resend\test\route.ts
      description: POST operation for webhooks\resend\test\route.ts
      tags:
        - webhooks\resend\test\route.ts
      responses:
        '200':
          description: Success
        '500':
          $ref: '#/components/responses/InternalError'
  /api/whatsapp/link:
    get:
      summary: List whatsapp\link\route.ts
      description: GET operation for whatsapp\link\route.ts
      tags:
        - whatsapp\link\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create whatsapp\link\route.ts
      description: POST operation for whatsapp\link\route.ts
      tags:
        - whatsapp\link\route.ts
      responses:
        '200':
          description: Success
        '400':
          $ref: '#/components/responses/ValidationError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  securitySchemes:
    AdminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Admin authentication using Bearer token with x-admin-email header
  schemas:
    Locale:
      type: string
      enum:
        - es
        - en
        - pt
      description: Supported locale codes
    ServiceType:
      type: string
      enum:
        - charter
        - empty_legs
        - multicity
        - helicopter
        - medical
        - cargo
        - other
      description: Type of aviation service requested
    QuoteStatus:
      type: string
      enum:
        - pending
        - processing
        - quoted
        - converted
        - closed
      description: Status of a quote request
    AdditionalService:
      type: string
      enum:
        - international_support
        - country_documentation
        - pet_friendly_transport
        - ground_transfer_driver
        - premium_catering
        - vip_lounge_fbo
        - customs_immigration_assist
      description: Additional services that can be requested
  responses:
    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Validation failed
              details:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    path:
                      type: array
                      items:
                        oneOf:
                          - type: string
                          - type: integer
                    message:
                      type: string
    RateLimitError:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Rate limit exceeded. Maximum 7 requests per hour.
    UnauthorizedError:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Authentication required
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Resource not found
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Internal server error
